rscodeio::install_theme()
print(a)
print(a)
a = 1+1
print(a)
install.packages("jsonlite", type="source")
install.packages("multilinguer")
library(multilinguer)
library(multilinguer)
library(multilinguer)
library(multilinguer)
library(multilinguer)
install_jdk()
multilinguer::install_jdk()
multilinguer::install_jdk()
install.packages("rJava")
rJava::.jinit()
library(multilinguer)
install.packages("multilinguer")
install.packages("multilinguer")
library(multilinguer)
library(multilinguer)
multilinguer::install_jdk()
rJava::.jinit()
install.packages(c("hash", "tau", "Sejong", "RSQLite", "devtools", "bit", "rex", "lazyeval", "htmlwidgets", "crosstalk", "promises", "later", "sessioninfo", "xopen", "bit64", "blob", "DBI", "memoise", "plogr", "covr", "DT", "rcmdcheck", "rversions"), type = "binary")
install.packages("remotes")
remotes::install_github('haven-jeon/KoNLP', upgrade = "never", INSTALL_opts=c("--no-multiarch"))
library(KoNLP)
library(rJava)
library(KoNLP)
library(KoNLP)
remotes::install_github('haven-jeon/KoNLP', upgrade = "never", INSTALL_opts=c("--no-multiarch"))
library(KoNLP)
a= " 바람이 부는 날에는 빈대떡을 먹고 싶다"
extractNoun(a)
library(KoNLP)
library(rJava)
library(KoNLP)
